class VisionMixin:
    def wait_until_image_appear(self): ...
    def wait_until_image_dissapear(self): ...
    def count_images(self): ...
    def image_exists(self): ...
    def wait_one_of_multiple_images(self): ...
    def wait_multiple_images(self): ...

    def _highlight(self):...
    def _get_image_region(self): ...