[project]
name = "inovarobotsikuli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "robotframework>=7.3.2",
    "robotframework-sikulilibrary>=2.0.5",
]
