# Portuguese (Brazil) keyword names and documentation  
# File: pt_BR.toml

[wait_until_image_appear]
robot_name = "Aguardar Até Imagem Aparecer"
doc_string = """Aguarda até que a imagem especificada apareça na tela.

Argumentos:
    image: Caminho para o arquivo de imagem a aguardar
    timeout: Tempo máximo para aguardar em segundos (tem padrão da config)
    similarity: Precisão de correspondência da imagem 0.0-1.0 (tem padrão da config)
    roi: Região de Interesse - caminho da imagem ou coordenadas [x, y, w, h] (pode ser None)

Nota:
    timeout e similarity têm valores garantidos pelo signature_utils.
"""